# Generated by Django 4.2 on 2023-05-01 19:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Contender Name')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_no', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Macth Number')),
                ('team_1', models.CharField(choices=[('CSK', 'Chennai Super Kings'), ('DC', 'Delhi Capitals'), ('GT', 'Gujrat Titans'), ('KKR', 'Kolkata Knight Riders'), ('LSG', 'Lucknow Super Giants'), ('MI', 'Mumbai Indians'), ('KIXP', 'Punjab Kings'), ('RR', 'Rajasthan Royals'), ('RCB', 'Royal Challengers Bangalore'), ('SRH', 'Sunrisers Hyderabad')], max_length=256, verbose_name='Team Name')),
                ('team_2', models.CharField(choices=[('CSK', 'Chennai Super Kings'), ('DC', 'Delhi Capitals'), ('GT', 'Gujrat Titans'), ('KKR', 'Kolkata Knight Riders'), ('LSG', 'Lucknow Super Giants'), ('MI', 'Mumbai Indians'), ('KIXP', 'Punjab Kings'), ('RR', 'Rajasthan Royals'), ('RCB', 'Royal Challengers Bangalore'), ('SRH', 'Sunrisers Hyderabad')], max_length=256, verbose_name='Team Name')),
            ],
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True)),
                ('contender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.contender')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.match')),
            ],
        ),
        migrations.CreateModel(
            name='LegendCupScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=10)),
                ('contender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.contender')),
            ],
        ),
    ]
