# Generated by Django 4.2 on 2023-05-01 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchscore',
            name='contender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contender'),
        ),
        migrations.AlterField(
            model_name='matchscore',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.match'),
        ),
        migrations.AlterField(
            model_name='matchscore',
            name='score',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')]),
        ),
    ]
