# Generated by Django 4.2 on 2023-05-01 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_matchscore_contender_alter_matchscore_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchscore',
            name='contender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.contender'),
        ),
        migrations.AlterField(
            model_name='matchscore',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.match'),
        ),
        migrations.AlterField(
            model_name='matchscore',
            name='score',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7')], null=True),
        ),
    ]
