# Generated by Django 4.2 on 2024-04-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_legendcupscore_options_alter_match_team_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchscore',
            name='score',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (0, 0)], null=True),
        ),
    ]
